name: Build Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.6'
    
    - name: Build Plugin
      run: gradle buildPlugin
    
    - name: Upload Plugin
      uses: actions/upload-artifact@v4
      with:
        name: plugin-zip
        path: build/distributions/*.zip
